# Imports

In [14]:
import pandas as pd
import numpy as np

# read the DFs

In [15]:
autos = pd.read_csv('../Quelldateien/autos_scraped.csv') #csv of scraped EV-listings
autos.head(5)
print(autos.shape)

(2314, 7)

In [16]:
plz = pd.read_csv('../Quelldateien/plz_gemeinde.csv') #csv with Names of "Gemeinden" and Postalcodes
print(plz.shape)
plz.head(5)

(4931, 5)

     PLZ4  %_IN_GDE KTKZ  GDENR             GDENAMK
0  8914.0    100.00   ZH    1.0     Aeugst am Albis
1  8909.0     14.34   ZH    2.0  Affoltern am Albis
2  8910.0     85.66   ZH    2.0  Affoltern am Albis
3  8906.0    100.00   ZH    3.0          Bonstetten
4  6340.0      0.77   ZH    4.0     Hausen am Albis

# Prepare the DFs

In [17]:
print(plz.shape)
plz = plz.drop_duplicates('PLZ4')
plz

(4931, 5)

        PLZ4  %_IN_GDE KTKZ   GDENR             GDENAMK
0     8914.0    100.00   ZH     1.0     Aeugst am Albis
1     8909.0     14.34   ZH     2.0  Affoltern am Albis
2     8910.0     85.66   ZH     2.0  Affoltern am Albis
3     8906.0    100.00   ZH     3.0          Bonstetten
4     6340.0      0.77   ZH     4.0     Hausen am Albis
...      ...       ...  ...     ...                 ...
4913  2946.0     30.35   JU  6810.0          La Baroche
4914  2947.0     27.66   JU  6810.0          La Baroche
4915  2953.0     18.89   JU  6810.0          La Baroche
4916  2954.0     17.20   JU  6810.0          La Baroche
4917     NaN       NaN  NaN     NaN                 NaN

[3185 rows x 5 columns]

In [18]:
df_merged_one = pd.merge(left=autos, right=plz, how='left', left_on='plz', right_on='PLZ4')
print(df_merged_one.shape)
df_merged_one

(2314, 12)

,web-scraper-order,web-scraper-start-url,Preis,plz,jahr,ps-stand,Farbe,PLZ4,%_IN_GDE,KTKZ,GDENR,GDENAMK
0,1669622809-189,https://www.autolina.ch/elektro-auto,49'650,8640,NaN,231.0,silber,8640.0,3.91,SZ,1322.0,Freienbach
1,1669622809-190,https://www.autolina.ch/elektro-auto,42'500,6464,2022.0,204.0,weiss,6464.0,0.36,UR,1205.0,BÃ¼rglen (UR)
2,1669622809-191,https://www.autolina.ch/elektro-auto,70'200,8807,NaN,325.0,weiss,8807.0,18.75,SZ,1322.0,Freienbach
3,1669622809-192,https://www.autolina.ch/elektro-auto,44'900,1184,2019.0,513.0,weiss,1184.0,100.00,VD,5858.0,Luins
4,1669622809-193,https://www.autolina.ch/elektro-auto,68'990,1920,NaN,408.0,sonstiges,1920.0,95.44,VS,6136.0,Martigny
...,...,...,...,...,...,...,...,...,...,...,...,...
2309,1669622809-2498,https://www.autolina.ch/elektro-auto,112'790,4310,2022.0,503.0,schwarz,4310.0,98.50,AG,4258.0,Rheinfelden
2310,1669622809-2499,https://www.autolina.ch/elektro-auto,45'700,9630,NaN,204.0,blau,9630.0,1.19,SG,3378.0,Neckertal
2311,1669622809-2500,https://www.autolina.ch/elektro-auto,49'800,3322,2022.0,218.0,blau,3322.0,100.00,BE,543.0,Mattstetten
2312,1669622809-2501,https://www.autolina.ch/elektro-auto,41'875,8820,NaN,122.0,weiss,8820.0,62.30,ZH,293.0,WÃ¤denswil
2313,1669622809-2502,https://www.autolina.ch/elektro-auto,86'100,8706,2021.0,503.0,grau,8706.0,100.00,ZH,156.0,Meilen

In [19]:
BFS_Nummer = pd.read_excel('../Quelldateien/Gemeindestand.xlsx') #file with codes of all Bezirke
print(BFS_Nummer.shape)
BFS_Nummer.head(5)

(2145, 7)

,Hist.-Nummer,Kanton,Bezirks-nummer,Bezirksname,BFS Gde-nummer,Gemeindename,Datum der Aufnahme
0,13256,ZH,101,Affoltern,1,Aeugst am Albis,1976-11-15
1,11742,ZH,101,Affoltern,2,Affoltern am Albis,1848-09-12
2,11801,ZH,101,Affoltern,3,Bonstetten,1848-09-12
3,11992,ZH,101,Affoltern,4,Hausen am Albis,1911-01-01
4,12249,ZH,101,Affoltern,5,Hedingen,1848-09-12

In [20]:
df_merged = pd.merge(left=df_merged_one, right=BFS_Nummer, how='left', left_on='GDENAMK', right_on='Gemeindename')
print(df_merged.shape)
df_merged.head(5)

(2314, 19)

,web-scraper-order,web-scraper-start-url,Preis,plz,jahr,ps-stand,Farbe,PLZ4,%_IN_GDE,KTKZ,GDENR,GDENAMK,Hist.-Nummer,Kanton,Bezirks-nummer,Bezirksname,BFS Gde-nummer,Gemeindename,Datum der Aufnahme
0,1669622809-189,https://www.autolina.ch/elektro-auto,49'650,8640,NaN,231.0,silber,8640.0,3.91,SZ,1322.0,Freienbach,11961.0,SZ,503.0,HÃ¶fe,1322.0,Freienbach,1848-09-12
1,1669622809-190,https://www.autolina.ch/elektro-auto,42'500,6464,2022.0,204.0,weiss,6464.0,0.36,UR,1205.0,BÃ¼rglen (UR),11506.0,UR,400.0,Kt. Uri,1205.0,BÃ¼rglen (UR),1848-09-12
2,1669622809-191,https://www.autolina.ch/elektro-auto,70'200,8807,NaN,325.0,weiss,8807.0,18.75,SZ,1322.0,Freienbach,11961.0,SZ,503.0,HÃ¶fe,1322.0,Freienbach,1848-09-12
3,1669622809-192,https://www.autolina.ch/elektro-auto,44'900,1184,2019.0,513.0,weiss,1184.0,100.00,VD,5858.0,Luins,14638.0,VD,2228.0,Nyon,5858.0,Luins,2006-09-01
4,1669622809-193,https://www.autolina.ch/elektro-auto,68'990,1920,NaN,408.0,sonstiges,1920.0,95.44,VS,6136.0,Martigny,16602.0,VS,2307.0,Martigny,6136.0,Martigny,2021-01-01

In [21]:
print(df_merged.isna().sum())
df_merged = df_merged.dropna(subset=['PLZ4', 'BFS Gde-nummer'])

web-scraper-order           0
web-scraper-start-url       0
Preis                       0
plz                         0
jahr                     1313
ps-stand                   24
Farbe                      24
PLZ4                       92
%_IN_GDE                   92
KTKZ                       92
GDENR                      92
GDENAMK                    92
Hist.-Nummer              101
Kanton                    101
Bezirks-nummer            101
Bezirksname               101
BFS Gde-nummer            101
Gemeindename              101
Datum der Aufnahme        101
dtype: int64

In [22]:
df_merged = df_merged.astype({"BFS Gde-nummer":int})

In [23]:
df_merged.head(2)

,web-scraper-order,web-scraper-start-url,Preis,plz,jahr,ps-stand,Farbe,PLZ4,%_IN_GDE,KTKZ,GDENR,GDENAMK,Hist.-Nummer,Kanton,Bezirks-nummer,Bezirksname,BFS Gde-nummer,Gemeindename,Datum der Aufnahme
0,1669622809-189,https://www.autolina.ch/elektro-auto,49'650,8640,NaN,231.0,silber,8640.0,3.91,SZ,1322.0,Freienbach,11961.0,SZ,503.0,HÃ¶fe,1322,Freienbach,1848-09-12
1,1669622809-190,https://www.autolina.ch/elektro-auto,42'500,6464,2022.0,204.0,weiss,6464.0,0.36,UR,1205.0,BÃ¼rglen (UR),11506.0,UR,400.0,Kt. Uri,1205,BÃ¼rglen (UR),1848-09-12

# Safe DF as a new csv

In [24]:
df_merged.to_csv('../Ausgabedateien/autos_aufbereitet.csv')

# Jupyter notebook --footer info

In [25]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')

-----------------------------------
NT
Windows | 10
Datetime: 2022-12-26 12:09:06
Python Version: 3.10.1
-----------------------------------